version: 2

updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
      time: "04:00"
    cooldown:
      default-days: 7

    target-branch: "develop"

    commit-message:
      prefix: "deps"

    open-pull-requests-limit: 5

    ignore:
      - dependency-name: "AutoMapper"
      - dependency-name: "AutoMapper.*"
      - dependency-name: "MediatR"
      - dependency-name: "MediatR.*"

    groups:
      microsoft-dotnet:
        patterns:
          - "Microsoft.*"
          - "System.*"
      aspire:
        patterns:
          - "Aspire.*"
          - "CommunityToolkit.Aspire.*"
      all-other-dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "Microsoft.*"
          - "System.*"
          - "Aspire.*"
          - "CommunityToolkit.Aspire.*"
          - "AutoMapper"
          - "AutoMapper.*"
          - "MediatR"
          - "MediatR.*"