<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <RootNamespace>Cfo.Cats.Consumers</RootNamespace>
        <AssemblyName>Cfo.Cats.Consumers</AssemblyName>
        <UserSecretsId>cfo-cats-consumers</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Application\Application.csproj" />
        <ProjectReference Include="..\Infrastructure\Infrastructure.csproj" />
        <ProjectReference Include="..\Aspire\Cats.ServiceDefaults\Cats.ServiceDefaults.csproj" />
    </ItemGroup>

    <ItemGroup>
        <!-- Embed excel templates -->
        <Content Include="..\Server.UI\Files\**\*.*" LinkBase="Files" CopyToOutputDirectory="Always" CopyToPublishDirectory="Always" />
    </ItemGroup>

</Project>
