apiVersion: v2
name: cats
description: |
  HMPPS - Case Assessment and Tracking System (CATS)
type: application

# Version of this chart. Bump on every change to the chart/values.
version: "0.1.0"

# Mirrors the application version; the running image is selected via image tags at deploy time.
appVersion: "0.1.0"

dependencies:
  - name: generic-service
    version: "3.17.5"
    repository: https://ministryofjustice.github.io/hmpps-helm-charts

  # https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
  - name: generic-prometheus-alerts
    version: "1.17.2"
    repository: https://ministryofjustice.github.io/hmpps-helm-charts
