app:
  replicaCount: 3
  ingress:
    host: cfocats-staging.live.cloud-platform.service.justice.gov.uk
  env:
    DOTNET_ENVIRONMENT: "Staging"
    Sentry__Environment: "Staging-CloudPlatform"

worker:
  replicaCount: 1
  env:
    DOTNET_ENVIRONMENT: "Staging"
    Sentry__Environment: "Staging-CloudPlatform"
    Features__PresenceHub__RelayUserPresenceNotifications: "false"

# RDS bridge - disabled in non-development environments
rdsPortForward:
  enabled: false

# todo: enable prometheus alerts
# generic-prometheus-alerts:
#   alertSeverity: cfo-alerts-nonprod
