// <auto-generated />
using System;
using Cfo.Cats.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cfo.Cats.Migrators.MSSQL.ManagementInformationMigrations
{
    [DbContext(typeof(ManagementInformationDbContext))]
    [Migration("20241223192808_NewTables")]
    partial class NewTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Cfo.Cats.Domain.Entities.ManagementInformation.ActivityPayment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ActivityApproved")
                        .HasColumnType("date");

                    b.Property<string>("ActivityCategory")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("ActivityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActivityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ContractId")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EligibleForPayment")
                        .HasColumnType("bit");

                    b.Property<string>("IneligibilityReason")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("LocationType")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("ParticipantId")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ParticipantId", "ContractId")
                        .HasDatabaseName("ix_ActivityPayment_ParticipantId");

                    b.ToTable("ActivityPayment", "Activities");
                });

            modelBuilder.Entity("Cfo.Cats.Domain.Entities.ManagementInformation.DateDimension", b =>
                {
                    b.Property<DateTime>("TheDate")
                        .HasColumnType("date");

                    b.Property<bool>("Has53ISOWeeks")
                        .HasColumnType("bit");

                    b.Property<bool>("Has53Weeks")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLeapYear")
                        .HasColumnType("bit");

                    b.Property<bool>("IsWeekend")
                        .HasColumnType("bit");

                    b.Property<string>("MMYYYY")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("Style101")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Style103")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Style112")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Style120")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("TheDay")
                        .HasColumnType("int");

                    b.Property<string>("TheDayName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TheDayOfWeek")
                        .HasColumnType("int");

                    b.Property<int>("TheDayOfWeekInMonth")
                        .HasColumnType("int");

                    b.Property<int>("TheDayOfYear")
                        .HasColumnType("int");

                    b.Property<string>("TheDaySuffix")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<DateTime>("TheFirstOfMonth")
                        .HasColumnType("date");

                    b.Property<DateTime>("TheFirstOfNextMonth")
                        .HasColumnType("date");

                    b.Property<DateTime>("TheFirstOfQuarter")
                        .HasColumnType("date");

                    b.Property<DateTime>("TheFirstOfWeek")
                        .HasColumnType("date");

                    b.Property<DateTime>("TheFirstOfYear")
                        .HasColumnType("date");

                    b.Property<int>("TheISOYear")
                        .HasColumnType("int");

                    b.Property<int>("TheISOweek")
                        .HasColumnType("int");

                    b.Property<DateTime>("TheLastOfMonth")
                        .HasColumnType("date");

                    b.Property<DateTime>("TheLastOfNextMonth")
                        .HasColumnType("date");

                    b.Property<DateTime>("TheLastOfQuarter")
                        .HasColumnType("date");

                    b.Property<DateTime>("TheLastOfWeek")
                        .HasColumnType("date");

                    b.Property<DateTime>("TheLastOfYear")
                        .HasColumnType("date");

                    b.Property<int>("TheMonth")
                        .HasColumnType("int");

                    b.Property<string>("TheMonthName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TheQuarter")
                        .HasColumnType("int");

                    b.Property<int>("TheWeek")
                        .HasColumnType("int");

                    b.Property<int>("TheWeekOfMonth")
                        .HasColumnType("int");

                    b.Property<int>("TheYear")
                        .HasColumnType("int");

                    b.HasKey("TheDate");

                    b.ToTable("DateDimension", (string)null);
                });

            modelBuilder.Entity("Cfo.Cats.Domain.Entities.ManagementInformation.EnrolmentPayment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Approved")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ConsentAdded")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ConsentSigned")
                        .HasColumnType("datetime2");

                    b.Property<string>("ContractId")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EligibleForPayment")
                        .HasColumnType("bit");

                    b.Property<string>("IneligibilityReason")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("LocationType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasDefaultValue("");

                    b.Property<string>("ParticipantId")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<string>("ReferralRoute")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("SubmissionToAuthority")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SubmissionToPqa")
                        .HasColumnType("datetime2");

                    b.Property<int>("SubmissionsToAuthority")
                        .HasColumnType("int");

                    b.Property<string>("SupportWorker")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ParticipantId");

                    b.ToTable("EnrolmentPayment", "Attachments");
                });

            modelBuilder.Entity("Cfo.Cats.Domain.Entities.ManagementInformation.InductionPayment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Approved")
                        .HasColumnType("datetime2");

                    b.Property<string>("ContractId")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EligibleForPayment")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Induction")
                        .HasColumnType("datetime2");

                    b.Property<string>("IneligibilityReason")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("LocationType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasDefaultValue("");

                    b.Property<string>("ParticipantId")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<string>("SupportWorker")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ParticipantId", "ContractId")
                        .HasDatabaseName("ix_InductionPayment_ParticipantId");

                    b.ToTable("InductionPayment", "Attachments");
                });
#pragma warning restore 612, 618
        }
    }
}
