


IF NOT EXISTS (SELECT TOP(1) [Code] FROM [Dms].[LocationMapping])
BEGIN

    INSERT INTO Dms.LocationMapping (Code, CodeType, Description, DeliveryRegion, LocationId) 
    VALUES 
    (N'ACI', N'Prison', N'Altcourse', N'North West', 4),
    (N'AGI', N'Prison', N'Askham Grange', N'Yorkshire and Humberside', 29),
    (N'ALL', N'Probation', N'No Trust or Trust Unknown', N'National', null),
    (N'ASI', N'Prison', N'Ashfield', N'South West', null),
    (N'ASP', N'Probation', N'Avon & Somerset', N'South West Community', 97),
    (N'AYI', N'Prison', N'Aylesbury', N'South East', 81),
    (N'BAI', N'Prison', N'Belmarsh', N'London', null),
    (N'BCI', N'Prison', N'Buckley Hall', N'North West', 6),
    (N'BED', N'Probation', N'Bedfordshire', N'East Of England Community', 95),
    (N'BFI', N'Prison', N'Bedford', N'East of England', 51),
    (N'BHI', N'Prison', N'Blantyre House', N'South East', null),
    (N'BLI', N'Prison', N'Bristol', N'South West', 70),
    (N'BMI', N'Prison', N'Birmingham', N'West Midlands', 33),
    (N'BNI', N'Prison', N'Bullingdon', N'South East', 82),
    (N'BRI', N'Prison', N'Bure', N'East of England', null),
    (N'BSI', N'Prison', N'Brinsford', N'West Midlands', 34),
    (N'BWI', N'Prison', N'Berwyn', N'Unknown', null),
    (N'BXI', N'Prison', N'Brixton', N'London', 62),
    (N'BZI', N'Prison', N'Bronzefield', N'South East', 66),
    (N'C01', N'Probation', N'CPA Northumbria', N'North East Community', 91),
    (N'C02', N'Probation', N'CPA Cumbria and Lancashire', N'North West Community', 90),
    (N'C03', N'Probation', N'CPA Durham Tees Valley', N'North East Community', 91),
    (N'C04', N'Probation', N'CPA Humber Lincs & N Yorks', N'Yorkshire and Humberside Community', 92),
    (N'C05', N'Probation', N'CPA West Yorkshire', N'Yorkshire and Humberside Community', 92),
    (N'C06', N'Probation', N'CPA Merseyside', N'North West Community', 90),
    (N'C07', N'Probation', N'CPA Cheshire and Gtr Manchester', N'North West Community', 90),
    (N'C08', N'Probation', N'CPA Derby Leics Notts Rutland', N'East Midlands Community', 94),
    (N'C09', N'Probation', N'CPA South Yorkshire', N'Yorkshire and Humberside Community', 92),
    (N'C10', N'Probation', N'CPA Wales', N'Unknown', null),
    (N'C11', N'Probation', N'CPA Staff and West Mids', N'West Midlands Community', 93),
    (N'C12', N'Probation', N'CPA Warwickshire and West Mercia', N'West Midlands Community', 93),
    (N'C13', N'Probation', N'CPA BeNCH', N'National', null),
    (N'C14', N'Probation', N'CPA Norfolk and Suffolk', N'East Of England Community', 95),
    (N'C15', N'Probation', N'CPA Brist Gloucs Somerset Wilts', N'South West Community', 97),
    (N'C16', N'Probation', N'CPA Thames Valley', N'South East Community', 98),
    (N'C17', N'Probation', N'CPA London', N'London Community', 96),
    (N'C18', N'Probation', N'CPA Essex', N'East Of England Community', 95),
    (N'C19', N'Probation', N'CPA Dorset Devon and Cornwall', N'South West Community', 97),
    (N'C20', N'Probation', N'CPA Hampshire and Isle of Wight', N'South East Community', 98),
    (N'C21', N'Probation', N'CPA Kent, Surrey & Sussex', N'South East Community', 98),
    (N'CBS', N'Probation', N'Cambridgeshire &Peterborough', N'East Of England Community', 95),
    (N'CDI', N'Prison', N'Chelmsford', N'East of England', 52),
    (N'CFI', N'Prison', N'Cardiff', N'Unknown', null),
    (N'CHS', N'Probation', N'Cheshire', N'North West Community', 90),
    (N'CKI', N'Prison', N'Cookham Wood', N'South East', null),
    (N'CLI', N'Prison', N'Coldingley', N'South East', null),
    (N'CMB', N'Probation', N'Cumbria', N'North West Community', 90),
    (N'CWI', N'Prison', N'Channings Wood', N'South West', 71),
    (N'DAI', N'Prison', N'Dartmoor', N'South West', 72),
    (N'DBS', N'Probation', N'Derbyshire', N'East Midlands Community', 94),
    (N'DCP', N'Probation', N'Devon & Cornwall', N'South West Community', 97),
    (N'DGI', N'Prison', N'Dovegate', N'West Midlands', 35),
    (N'DHI', N'Prison', N'Drake Hall', N'West Midlands', 32),
    (N'DMI', N'Prison', N'Durham', N'North East', 17),
    (N'DNI', N'Prison', N'Doncaster', N'Yorkshire and Humberside', 23),
    (N'DRS', N'Probation', N'Dorset', N'South West Community', 97),
    (N'DTI', N'Prison', N'Deerbolt', N'North East', null),
    (N'DTV', N'Probation', N'Durham and Tees Valley', N'North East Community', 91),
    (N'DVI', N'Prison', N'Dover', N'South East', null),
    (N'DWI', N'Prison', N'Downview', N'South East', 67),
    (N'EEI', N'Prison', N'Erlestoke', N'South West', null),
    (N'EHI', N'Prison', N'Standford Hill', N'South East', 85),
    (N'ESI', N'Prison', N'East Sutton Park', N'South East', 89),
    (N'ESX', N'Probation', N'Essex', N'East Of England Community', 95),
    (N'EWI', N'Prison', N'Eastwood Park', N'South West', 76),
    (N'EXI', N'Prison', N'Exeter', N'South West', 69),
    (N'EYI', N'Prison', N'Elmley', N'South East', 78),
    (N'FBI', N'Prison', N'Forest Bank', N'North West', 3),
    (N'FDI', N'Prison', N'Ford', N'South East', 83),
    (N'FEI', N'Prison', N'Fosse Way', N'East Midlands', null),
    (N'FHI', N'Prison', N'Foston Hall', N'East Midlands', 48),
    (N'FKI', N'Prison', N'Frankland', N'North East', null),
    (N'FMI', N'Prison', N'Feltham', N'London', 63),
    (N'FNI', N'Prison', N'Full Sutton', N'Yorkshire and Humberside', 26),
    (N'FSI', N'Prison', N'Featherstone', N'West Midlands', 31),
    (N'FWI', N'Prison', N'Five Wells', N'East Midlands', 42),
    (N'FYI', N'Prison', N'Feltham', N'London', 63),
    (N'GCS', N'Probation', N'Gloucestershire', N'South West Community', 97),
    (N'GHI', N'Prison', N'Garth', N'North West', null),
    (N'GMI', N'Prison', N'Guys Marsh', N'South West', 74),
    (N'GNI', N'Prison', N'Grendon', N'South East', null),
    (N'GPI', N'Prison', N'Glen Parva', N'East Midlands', null),
    (N'GTI', N'Prison', N'Gartree', N'East Midlands', null),
    (N'HBI', N'Prison', N'Hollesley Bay', N'East of England', 54),
    (N'HBS', N'Probation', N'Humberside', N'Yorkshire and Humberside Community', 92),
    (N'HCI', N'Prison', N'Huntercombe', N'South East', null),
    (N'HDI', N'Prison', N'Hatfield', N'Yorkshire and Humberside', 27),
    (N'HEI', N'Prison', N'Hewell', N'West Midlands', 36),
    (N'HFS', N'Probation', N'Hertfordshire', N'East Of England Community', 95),
    (N'HHI', N'Prison', N'Holme House', N'North East', 15),
    (N'HII', N'Prison', N'Hindley', N'North West', 11),
    (N'HLI', N'Prison', N'Hull', N'Yorkshire and Humberside', 25),
    (N'HMI', N'Prison', N'Humber', N'Yorkshire and Humberside', 22),
    (N'HOI', N'Prison', N'High Down', N'South East', 59),
    (N'HPI', N'Prison', N'Highpoint', N'East of England', 53),
    (N'HPS', N'Probation', N'Hampshire', N'South East Community', 98),
    (N'HRI', N'Prison', N'Haslar', N'South East', null),
    (N'HVI', N'Prison', N'Haverigg', N'North West', 10),
    (N'HYI', N'Prison', N'Holloway', N'London', null),
    (N'ISI', N'Prison', N'Isis', N'London', 64),
    (N'IWI', N'Prison', N'Isle Of Wight', N'South East', null),
    (N'IWI', N'Probation', N'Isle Of Wight', N'South East Community', 98),
    (N'KMI', N'Prison', N'Kirkham', N'North West', 12),
    (N'KNT', N'Probation', N'Kent', N'South East Community', 98),
    (N'KTI', N'Prison', N'Kennet', N'North West', null),
    (N'KVI', N'Prison', N'Kirklevington Grange', N'North East', 18),
    (N'LCI', N'Prison', N'Leicester', N'East Midlands', 16),
    (N'LCS', N'Probation', N'Lancashire', N'North West Community', 90),
    (N'LDN', N'Probation', N'London', N'London Community', 96),
    (N'LEI', N'Prison', N'Leeds', N'Yorkshire and Humberside', 24),
    (N'LFI', N'Prison', N'Lancaster Farms', N'North West', 2),
    (N'LGI', N'Prison', N'Lowdham Grange', N'East Midlands', null),
    (N'LHI', N'Prison', N'Lindholme', N'Yorkshire and Humberside', 28),
    (N'LII', N'Prison', N'Lincoln', N'East Midlands', 43),
    (N'LLI', N'Prison', N'Long Lartin', N'West Midlands', null),
    (N'LNI', N'Prison', N'Low Newton', N'North East', 19),
    (N'LNS', N'Probation', N'Lincolnshire', N'East Midlands Community', 94),
    (N'LPI', N'Prison', N'Liverpool', N'North West', 7),
    (N'LTI', N'Prison', N'Littlehey', N'East of England', 55),
    (N'LTS', N'Probation', N'Leicestershire & Rutland', N'East Midlands Community', 94),
    (N'LWI', N'Prison', N'Lewes', N'South East', 79),
    (N'LYI', N'Prison', N'Leyhill', N'South West', 73),
    (N'MCG', N'Probation', N'Greater Manchester', N'North West Community', 90),
    (N'MDI', N'Prison', N'Moorland', N'Yorkshire and Humberside', 21),
    (N'MHI', N'Prison', N'Morton Hall', N'East Midlands', null),
    (N'MRI', N'Prison', N'Manchester', N'North West', 8),
    (N'MRS', N'Probation', N'Merseyside', N'North West Community', 90),
    (N'MSI', N'Prison', N'Maidstone', N'South East', null),
    (N'MTI', N'Prison', N'The Mount', N'East of England', 49),
    (N'MWI', N'Prison', N'Medway', N'South East', null),
    (N'N01', N'Probation', N'NPS North West', N'North West Community', 90),
    (N'N02', N'Probation', N'NPS North East', N'North East Community', 91),
    (N'N03', N'Probation', N'Wales', N'Unknown', null),
    (N'N04', N'Probation', N'NPS Midlands', N'National', null),
    (N'N05', N'Probation', N'NPS South West and South Central', N'National', null),
    (N'N06', N'Probation', N'NPS South East and Eastern', N'National', null),
    (N'N07', N'Probation', N'London', N'London Community', 96),
    (N'N21', N'Probation', N'External - London', N'London Community', 96),
    (N'N22', N'Probation', N'External - NPS Midlands', N'National', null),
    (N'N23', N'Probation', N'External - NPS North East', N'North East Community', 91),
    (N'N24', N'Probation', N'External - NPS North West', N'North West Community', 90),
    (N'N25', N'Probation', N'External - NPS South East & Estn', N'National', null),
    (N'N26', N'Probation', N'External - NPS South West & SC', N'National', null),
    (N'N27', N'Probation', N'External - Wales', N'Unknown', null),
    (N'N28', N'Probation', N'Ext - Greater Manchester', N'North West Community', 90),
    (N'N29', N'Probation', N'Ext - North West Region', N'North West Community', 90),
    (N'N30', N'Probation', N'Ext - West Midlands Region', N'West Midlands Community', 93),
    (N'N31', N'Probation', N'Ext - East Midlands Region', N'East Midlands Community', 94),
    (N'N32', N'Probation', N'Ext - North East Region', N'North East Community', 91),
    (N'N33', N'Probation', N'Ext - Yorkshire and The Humber', N'Yorkshire and Humberside Community', 92),
    (N'N34', N'Probation', N'Ext - East of England', N'East Of England Community', 95),
    (N'N35', N'Probation', N'Ext - Kent Surrey Sussex', N'South East Community', 98),
    (N'N36', N'Probation', N'Ext - South West', N'South West Community', 97),
    (N'N37', N'Probation', N'Ext - South Central', N'South East Community', 98),
    (N'N40', N'Probation', N'Central Projects Team', N'National', null),
    (N'N41', N'Probation', N'National Responsibility Divison', N'National', null),
    (N'N43', N'Probation', N'National Security Division', N'National', null),
    (N'N50', N'Probation', N'Greater Manchester', N'North West Community', 90),
    (N'N51', N'Probation', N'North West Region', N'North West Community', 90),
    (N'N52', N'Probation', N'West Midlands Region', N'West Midlands Community', 93),
    (N'N53', N'Probation', N'East Midlands Region', N'East Midlands Community', 94),
    (N'N54', N'Probation', N'North East Region', N'North East Community', 91),
    (N'N55', N'Probation', N'Yorkshire and The Humber', N'Yorkshire and Humberside Community', 92),
    (N'N56', N'Probation', N'East of England', N'East Of England Community', 95),
    (N'N57', N'Probation', N'Kent Surrey Sussex Region', N'South East Community', 98),
    (N'N58', N'Probation', N'South West', N'South West Community', 97),
    (N'N59', N'Probation', N'South Central', N'South East Community', 98),
    (N'NBR', N'Probation', N'Northumbria', N'North East Community', 91),
    (N'NHI', N'Prison', N'New Hall', N'Yorkshire and Humberside', 30),
    (N'NHS', N'Probation', N'Nottinghamshire', N'East Midlands Community', 94),
    (N'NLI', N'Prison', N'Northumberland', N'North East', 16),
    (N'NMI', N'Prison', N'Nottingham', N'East Midlands', 41),
    (N'NSI', N'Prison', N'North Sea Camp', N'East Midlands', 44),
    (N'NSP', N'Probation', N'Norfolk and Suffolk', N'East Of England Community', 95),
    (N'NTS', N'Probation', N'Northamptonshire', N'East Midlands Community', 94),
    (N'NWI', N'Prison', N'Norwich', N'East of England', 56),
    (N'ONI', N'Prison', N'Onley', N'East Midlands', 45),
    (N'OUT', N'Prison', N'Outside Prison', N'National', null),
    (N'OWI', N'Prison', N'Oakwood', N'West Midlands', 37),
    (N'PBI', N'Prison', N'Peterborough', N'East of England', 50),
    (N'PDI', N'Prison', N'Portland', N'South West', 68),
    (N'PFI', N'Prison', N'Peterborough', N'East of England', 58),
    (N'PNI', N'Prison', N'Preston', N'North West', 5),
    (N'PRI', N'Prison', N'Parc', N'Unknown', null),
    (N'PVI', N'Prison', N'Pentonville', N'London', 65),
    (N'PYI', N'Prison', N'Parc', N'Unknown', null),
    (N'RCI', N'Prison', N'Rochester', N'South East', 77),
    (N'RHI', N'Prison', N'Rye Hill', N'East Midlands', null),
    (N'RNI', N'Prison', N'Ranby', N'East Midlands', 40),
    (N'RSI', N'Prison', N'Risley', N'North West', 1),
    (N'SDI', N'Prison', N'Send', N'South East', 88),
    (N'SFI', N'Prison', N'Stafford', N'West Midlands', null),
    (N'SHI', N'Prison', N'Stoke Heath', N'West Midlands', 38),
    (N'SKI', N'Prison', N'Stocken', N'East Midlands', 46),
    (N'SLI', N'Prison', N'Swaleside', N'South East', 86),
    (N'SNI', N'Prison', N'Swinfen Hall', N'West Midlands', 39),
    (N'SPI', N'Prison', N'Spring Hill', N'South East', 84),
    (N'SSP', N'Probation', N'Surrey and Sussex', N'South East Community', 98),
    (N'STI', N'Prison', N'Styal', N'North West', 14),
    (N'SUI', N'Prison', N'Sudbury', N'East Midlands', null),
    (N'SWI', N'Prison', N'Swansea', N'Unknown', null),
    (N'SWM', N'Probation', N'Staffordshire and West Midlands', N'West Midlands Community', 93),
    (N'T01', N'Probation', N'Migration artifact - do not use', N'National', null),
    (N'TCI', N'Prison', N'Thorn Cross', N'North West', 9),
    (N'TRN', N'Prison', N'In Transfer', N'National', null),
    (N'TSI', N'Prison', N'Thameside', N'London', 61),
    (N'TVP', N'Probation', N'Thames Valley', N'South East Community', 98),
    (N'UKI', N'Prison', N'Usk', N'Unknown', null),
    (N'UPI', N'Prison', N'Prescoed', N'Unknown', null),
    (N'VEI', N'Prison', N'The Verne', N'South West', 75),
    (N'WCI', N'Prison', N'Winchester', N'South East', 80),
    (N'WDI', N'Prison', N'Wakefield', N'Yorkshire and Humberside', null),
    (N'WEI', N'Prison', N'Wealstun', N'Yorkshire and Humberside', 20),
    (N'WHI', N'Prison', N'Woodhill', N'South East', 87),
    (N'WII', N'Prison', N'Warren Hill', N'East of England', null),
    (N'WLI', N'Prison', N'Wayland', N'East of England', 57),
    (N'WMI', N'Prison', N'Wymott', N'North West', 13),
    (N'WMP', N'Probation', N'West Mercia', N'West Midlands Community', 93),
    (N'WNI', N'Prison', N'Werrington', N'West Midlands', null),
    (N'WPT', N'Probation', N'Wales Probation Trust', N'Unknown', null),
    (N'WRI', N'Prison', N'Whitemoor', N'East of England', null),
    (N'WSI', N'Prison', N'Wormwood Scrubs', N'London', null),
    (N'WTI', N'Prison', N'Whatton', N'East Midlands', 47),
    (N'WTS', N'Probation', N'Wiltshire', N'South West Community', 97),
    (N'WWI', N'Prison', N'Wandsworth', N'London', 60),
    (N'WWS', N'Probation', N'Warwickshire', N'West Midlands Community', 93),
    (N'WYI', N'Prison', N'Wetherby', N'Yorkshire and Humberside', null),
    (N'XXX', N'Probation', N'ZZ BAST Public Provider 1', N'National', null),
    (N'YSN', N'Probation', N'York and North Yorkshire', N'Yorkshire and Humberside Community', 92),
    (N'YSS', N'Probation', N'South Yorkshire', N'Yorkshire and Humberside Community', 92),
    (N'YSW', N'Probation', N'West Yorkshire', N'Yorkshire and Humberside Community', 92),
    (N'ZMM', N'Probation', N'ZZ - Steria Monitoring Trust', N'National', null),
    (N'CAT1', N'Probation', N'North West Sticky', N'North West', 90),
    (N'CAT2', N'Probation', N'North East Sticky', N'North East', 91),
    (N'CAT3', N'Probation', N'Yorkshire and Humberside Sticky', N'Yorkshire and Humberside', 92),
    (N'CAT4', N'Probation', N'West Midlands Sticky', N'West Midlands', 93),
    (N'CAT5', N'Probation', N'East Midlands Sticky', N'East Midlands', 94),
    (N'CAT6', N'Probation', N'East Of England Sticky', N'East Of England', 95),
    (N'CAT7', N'Probation', N'London Sticky', N'London', 96),
    (N'CAT8', N'Probation', N'South West Sticky', N'South West', 97),
    (N'CAT9', N'Probation', N'South East Sticky', N'South East', 98);

END;