serviceAccountName: cfocats-prod

app:
  serviceAccountName: cfocats-prod
  replicaCount: 4
  ingress:
    host: cfocats-prod.live.cloud-platform.service.justice.gov.uk
    className: modsec
    # modsecurity_mode: On # Default to modsecurity_mode "DetectionOnly" until staging is tuned, then "On".

  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: "2"
      memory: 2Gi
  env:
    DOTNET_ENVIRONMENT: "Production"
    Sentry__Environment: "Production-CloudPlatform"

worker:
  serviceAccountName: cfocats-prod
  replicaCount: 1
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: "1"
      memory: 1Gi
  env:
    DOTNET_ENVIRONMENT: "Production"
    Sentry__Environment: "Production-CloudPlatform"
    Features__PresenceHub__RelayUserPresenceNotifications: "false"

# RDS bridge - disabled in non-development environments
rdsPortForward:
  enabled: false

# todo: enable prometheus alerts
# generic-prometheus-alerts:
#   alertSeverity: cfo-alerts
