{{- if .Values.rdsPortForward.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rds-port-forward-deployment
  labels:
    app: rds-port-forward
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rds-port-forward
  template:
    metadata:
      labels:
        app: rds-port-forward
    spec:
      serviceAccountName: {{ .Values.serviceAccountName }}

      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault

      containers:
        - name: rds-port-forward
          image: {{ .Values.rdsPortForward.image | quote }}

          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL

          ports:
            - containerPort: {{ .Values.rdsPortForward.localPort }}

          env:
            - name: REMOTE_HOST
              valueFrom:
                secretKeyRef:
                  name: rds-mssql-instance-output
                  key: rds_instance_address

            - name: LOCAL_PORT
              value: {{ .Values.rdsPortForward.localPort | quote }}

            - name: REMOTE_PORT
              value: {{ .Values.rdsPortForward.remotePort | quote }}
{{- end }}