{{- if .Values.redisPortForward.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-port-forward-deployment
  labels:
    app: redis-port-forward
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-port-forward
  template:
    metadata:
      labels:
        app: redis-port-forward
    spec:
      serviceAccountName: {{ .Values.serviceAccountName }}
      containers:
        - name: redis-port-forward
          image: {{ .Values.redisPortForward.image | quote }}
          ports:
            - containerPort: {{ .Values.redisPortForward.localPort }}   # this is your LOCAL_PORT inside the pod
          env:
            - name: REMOTE_HOST
              valueFrom:
                secretKeyRef:
                  name: elasticache-redis-instance-output
                  key: primary_endpoint_address
            - name: LOCAL_PORT
              value: {{ .Values.redisPortForward.localPort | quote }}    # what the pod listens on
            - name: REMOTE_PORT
              value: {{ .Values.redisPortForward.remotePort | quote }}   # Redis in the cloud
{{- end }}
