name: Create new release

on:
  workflow_dispatch:

permissions:
  contents: write   # required for pushing tags & publishing releases

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current branch
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@c2fa09f4bde5ebb9d1777cf28262a3eb3db3ced7
        with:
          dotnet-version: '10.0.x'

      - name: Dotnet Cake Script
        run: dotnet cake.cs --target Publish

      - name: Generate Version Tag
        id: version
        run: |
          set -euo pipefail
          TAG_NAME="v$(date +'%Y.%m.%d').${{ github.run_number }}"
          echo "tag=$TAG_NAME" >> $GITHUB_OUTPUT

      - name: Create Build Artifacts Archive
        run: zip -r "${{ steps.version.outputs.tag }}.zip" artifacts/

      - name: Create Git Tag and Push
        run: |
          set -euo pipefail
          git tag "${{ steps.version.outputs.tag }}" "${{ github.sha }}"
          git push origin "${{ steps.version.outputs.tag }}"

      - name: Create Release
        uses: softprops/action-gh-release@153bb8e04406b158c6c84fc1615b65b24149a1fe
        with:
          tag_name: ${{ steps.version.outputs.tag }}
          name: Release ${{ steps.version.outputs.tag }}
          files: "${{ steps.version.outputs.tag }}.zip"
          draft: false
          prerelease: false
          generate_release_notes: true
          fail_on_unmatched_files: true