name: .NET Core Unit Tests

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read  # required to checkout code

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          fetch-depth: 0

      - name: Setup .NET Core
        uses: actions/setup-dotnet@c2fa09f4bde5ebb9d1777cf28262a3eb3db3ced7
        with:
          dotnet-version: '10.0.x'

      - name: Cake Script
        run: dotnet cake.cs --Target Test